### PR TITLE
IN-859

### PR DESCRIPTION
**Pull request by jmarruff**
Allow any authenticated user to delete any staff member profile.

### CODE REVIEW

**Comment by jmarruff** [comment]
It looks like your text format for delegations was included in this change, which is probably okay. If you needed to revert just the text format changes you should be able to do that later.

**Review by ryanletulle — CHANGES_REQUESTED** [review]
A deployment is running. The delegation format is only temporary. We need to remove those permissions from the config file.

**Comment by jmarruff** [comment]
I can resubmit when the deployment is finished.

**Comment by ryanletulle** [comment]
> I can resubmit when the deployment is finished.

I disabled the ckeditor integration module to see if the deployment goes through then I will figure  out why the deployment is trying to uninstall that embedded content module when the ck int module needs it.

**Comment by jmarruff** [comment]
Never mind on this. Just creating a new one.

**Pull request closed without merging**
